### ISSUE TITLE
version 1.2.1 doesn't support minecraft 1.20.6

### ISSUE THREAD

**Issue by horseloyal** [vi945786/MobHealthIndicators#3]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'MobHealthIndicators' (healthindicators) 1.2.1 with any version that is compatible with:
		 - minecraft 1.20.6
More details:
	 - Mod 'MobHealthIndicators' (healthindicators) 1.2.1 requires version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by vi945786** [comment]
https://modrinth.com/mod/mobhealthindicators/version/XB1W4huu
